### ISSUE TITLE
Documentation request: IEEE13 Bus load flow

### ISSUE THREAD

**Issue by jeverdave** [NREL/OpenDSSDirect.py#50] opened 2019-02-09 06:20 UTC
### Versions

- [x] Python version: 
- [x] Python architecture: 
- [ ] Operating system and version: 
- [ ] OpenDSSDirect.py version number: 

### Bug

* **What is the current behavior?**

* **What is the expected behavior? What is the motivation / use case for changing the behavior?**

* **What are the steps to reproduce this bug? Please provide a minimal working example of the bug if possible.**

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by kdheepak** [comment] 2019-02-09 06:41
Duplicate of #49.

**Closed by kdheepak** 2019-02-09 06:41 UTC
